apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==       # base64 for: mongoadmin
  mongo-root-password: cGFzc3dvcmQxMjM=       # base64 for: password123
