apiVersion: v1
kind: Service
metadata:
  name: task42c-calculator-api-service
spec:
  selector:
    app: task42c-calculator-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
